name: 'New Relic Application Deployment Marker'
author: 'New Relic'
description: 'Apply a New Relic application change event marker to an application that is monitored by New Relic. 
  **Important Note:** Input requirements for this action vary depending on the `commandType` chosen.
  Please refer to the detailed documentation in the README for specific mandatory fields for each scenario.'
branding:
  icon: 'upload-cloud'
  color: 'green'
inputs:
  apiKey:
    description: 'Your New Relic User API Key.'
    required: true
  guid:
    description: 'Your New Relic entity GUID. This entity GUID should be for the entity you are tracking.'
    required: false
  version:
    description: 'Custom version information to add to the deployment marker - e.g. the latest tag.'
    required: false
  region:
    description: 'The geographical region for your New Relic account - US or EU. Default: US'
    required: false
    default: US
  description:
    description: 'Description stored with the deployment. Default: <none>'
    required: false
  changelog:
    description: 'Change log string stored with the deployment. Default: <none>'
    required: false
  commit:
    description: 'Commit for the deployment.'
    required: false
  deeplink:
    description: 'Deep link referencing the deployment.'
    required: false
  deploymenttype:
    description: 'The type of deployment this is conducting.'
    required: false
    default: BASIC
  user:
    description: 'The user creating the deployment. Default: `github.actor`'
    required: false
    default: '${{ github.actor }}'
  groupid:
    description: 'Group Id used to link deployments together.'
    required: false

  # --- NEW INPUTS FOR changeTrackingCreateEvent ---
  commandType:
    description: 'This field lets you track any change event. To use this new API mutation, you must set it to "changeTrackingCreateEvent".'
    required: false
    default: changeTrackingCreateDeployment
  category:
    description: 'The category of the change event. For a list of supported categories, [view our docs](https://docs.newrelic.com/docs/change-tracking/change-tracking-events/#supported-types)'
    required: false
  type:
    description: 'The type of the change event. For a list of supported types, [view our docs](https://docs.newrelic.com/docs/change-tracking/change-tracking-events/#supported-types)'
    required: false
  featureFlagId:
    description: 'The ID of the feature flag associated with the change event. This is required if the commandType is "changeTrackingCreateEvent" and the category is "Feature Flag".'
    required: false
  customAttributes:
    description: 'Represents key-value pairs of custom attributes in JavaScript object format. Attribute values can be of type string, boolean, or number. We store JavaScript number values to either Java long or double values. The main difference between JavaScript object format vs. JSON is that keys are not enclosed in quotes. For more information on limitations, [see our docs](https://docs.newrelic.com/docs/change-tracking/change-tracking-graphql/).'
    required: false
  entitySearch:
    description: 'Specify the entity to associate with the change tracking event via query.'
    required: false
  shortDescription:
    description: 'This field allows you to add your own context to help you quickly identify the change events sent to our system. This field should contain a concise description of the change suitable for showing in various parts of New Relic One. In the marker flag, shown when hovering over the pinhead of a "Changes" marker on a chart. In the "Activity stream" panels. If this field is left blank sensible defaults will be shown instead.'
    required: false
  timestamp:
    description: 'The start time of the change tracking event as the number of milliseconds since the Unix epoch. Defaults to now.'
    required: false
  validationFlags:
    description: 'Validation flags for the change event (e.g., "[ALLOW_CUSTOM_CATEGORY_OR_TYPE], [FAIL_ON_FIELD_LENGTH], [FAIL_ON_REST_API_FAILURES]"). Only applicable if commandType is "changeTrackingCreateEvent".'
    required: false

outputs:
  deploymentId:
    description: 'The id of the deployment'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    NEW_RELIC_API_KEY: ${{ inputs.apiKey }}
    NEW_RELIC_DEPLOYMENT_ENTITY_GUID: ${{ inputs.guid }}
    NEW_RELIC_REGION: ${{ inputs.region }}
    NEW_RELIC_DEPLOYMENT_USER: ${{ inputs.user }}
    NEW_RELIC_DEPLOYMENT_VERSION: ${{ inputs.version }}
    NEW_RELIC_DEPLOYMENT_CHANGE_LOG: ${{ inputs.changelog }}
    NEW_RELIC_DEPLOYMENT_COMMIT: ${{ inputs.commit}}
    NEW_RELIC_DEPLOYMENT_DESCRIPTION: ${{ inputs.description }}
    NEW_RELIC_DEPLOYMENT_DEEPLINK: ${{ inputs.deeplink }}
    NEW_RELIC_DEPLOYMENT_TYPE: ${{ inputs.deploymenttype }}
    NEW_RELIC_DEPLOYMENT_GROUP_ID: ${{ inputs.groupid }}

    # --- NEW ENVIRONMENT VARIABLES FOR changeTrackingCreateEvent ---
    NEW_RELIC_COMMAND_TYPE: ${{ inputs.commandType }}
    NEW_RELIC_CREATE_EVENT_ENTITY_SEARCH: ${{ inputs.entitySearch }}
    NEW_RELIC_CREATE_EVENT_CATEGORY: ${{ inputs.category }}
    NEW_RELIC_CREATE_EVENT_TYPE: ${{ inputs.type }}
    NEW_RELIC_CREATE_EVENT_FEATURE_FLAG_ID: ${{ inputs.featureFlagId }}
    NEW_RELIC_CREATE_EVENT_VALIDATION_FLAGS: ${{ inputs.dataHandlingFlags }}
    NEW_RELIC_CREATE_EVENT_CUSTOM_ATTRIBUTES: ${{ inputs.customAttributes }}
    NEW_RELIC_CREATE_EVENT_SHORT_DESCRIPTION: ${{ inputs.shortDescription }}
    NEW_RELIC_CREATE_EVENT_TIMESTAMP: ${{ inputs.timestamp }}
